export interface Dayinfo {
    id: number,
    sunrise: string,
    year_id: number,
    month_id: number,
    lagunam_id: number,
    lagunam_val: number,
    agas_val: number,
    date: boolean,
    tamil_date: number,
    day: string,
    natchathiram1_id: number,
    natchathiram1_val: number,
    natchathiram2_id: number,
    natchathiram2_val: number,
    sali_year: number,
    kali_year: number,
    kollam_year: number,
    hijiri_year: number,
    ayanam: number,
    patcham: number,
    thithi1: number,
    thithi1_val: number,
    thithi2: number,
    thithi2_val: number,
    namayogam1: number,
    namayogam1_val: number,
    namayogam2: number,
    namayogam2_val: number,
    karnam: number,
    karnam_val: number,
    thiyachiyam_val: number,
    sun_rise_id: number,
    sun_rise_month: number,
    sun_rise_date: number,
    sun_rise_value: string,
    eng_date: string
}
export interface mysqlRes {
    status: string,
    response: Dayinfo | any
}

export interface ChartInfo {
    // User Input
    inputDate?: string,
    birth_date?: string,
    birth_time?: string,
    time_type?: string,
    gender?: string,
    // Basic Info
    sunrise?: string,
    eng_date?: string,
    tamil_date?: any,
    tamil_month_id?: number,
    tamil_month?: string,
    basehrs?: string,
    birthNaligai?: number,
    // Yesterday, Today, Tomorrow Panjangam info
    before_date_details?: any,
    that_date_details?: any,
    next_date_details?: any,
    // Lagunam properties
    lagnam_id?: number,
    lagnam_name?: string,
    lagnam_val?: number,
    lagnam_total?: number,
    lagunam_eruppu?: number,
    lagunam_sell?: number,
    lagunam_palan?: string,
    amsalagunam_id?: number,
    // Natcharhiram properties
    natchathiram_id?: number,
    natchathiram_name?: number,
    natchathiram_patham?: number,
    natchathiram_patham_sell?: number,
    natchathiram_patham_eruppu?: number,
    natchathiram_palan?: number,
    athiantham?: number,
    // Thisai properties
    thisai_id?: number,
    thisai_name?: number,
    thisai_value?: number,
    // Other properties
    mirugam?: number,
    patchi?: number,
    maram?: number,
    ganam?: number,
    rajji?: number,
    nadi?: number
}