export interface Dayinfo {
    id: number,
    sunrise: string,
    year_id: number,
    month_id: number,
    lagunam_id: number,
    lagunam_val: number,
    agas_val: number,
    date: boolean,
    tamil_date: number,
    day: string,
    natchathiram1_id: number,
    natchathiram1_val: number,
    natchathiram2_id: number,
    natchathiram2_val: number,
    sali_year: number,
    kali_year: number,
    kollam_year: number,
    hijiri_year: number,
    ayanam: number,
    patcham: number,
    thithi1: number,
    thithi1_val: number,
    thithi2: number,
    thithi2_val: number,
    namayogam1: number,
    namayogam1_val: number,
    namayogam2: number,
    namayogam2_val: number,
    karnam: number,
    karnam_val: number,
    thiyachiyam_val: number,
    sun_rise_id: number,
    sun_rise_month: number,
    sun_rise_date: number,
    sun_rise_value: number,
    eng_date: string
}
export interface mysqlRes {
    status: string,
    response: Dayinfo | any
}